// supabase/functions/send-weekly-executive-summary/index.ts
// Automated weekly executive summary email
// Deploy with: supabase functions deploy send-weekly-executive-summary
// This function generates the summary and sends it automatically

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Initialize Supabase client with service role for admin access
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

    // Get executive email addresses from environment variable or request body
    // Format: EXECUTIVE_EMAILS=email1@example.com,email2@example.com
    let requestBody = {}
    try {
      const bodyText = await req.text()
      if (bodyText) {
        requestBody = JSON.parse(bodyText)
      }
    } catch (e) {
      // Request body is empty or invalid JSON, use defaults
    }
    
    const executiveEmails = (requestBody as any)?.emails || 
                            Deno.env.get('EXECUTIVE_EMAILS')?.split(',').map(e => e.trim()).filter(Boolean) || []
    
    if (executiveEmails.length === 0) {
      // Fallback: Try to get from database if you have a config table
      const { data: config } = await supabase
        .from('executive_email_config')
        .select('email_addresses')
        .single()
      
      if (config?.email_addresses && config.email_addresses.length > 0) {
        executiveEmails.push(...config.email_addresses)
      }
    }
    
    // Final check - if still no emails, return error
    if (executiveEmails.length === 0) {
      return new Response(
        JSON.stringify({ 
          error: 'No executive email addresses configured. Set EXECUTIVE_EMAILS environment variable or create executive_email_config table.' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Calculate date range for last 7 days
    const end = new Date()
    const start = new Date()
    start.setDate(start.getDate() - 6)
    const startDate = start.toISOString().split('T')[0]
    const endDate = end.toISOString().split('T')[0]

    // Aggregate weekly data
    const { data: reports, error: reportsError } = await supabase
      .from('daily_tickets')
      .select('*')
      .gte('date', startDate)
      .lte('date', endDate)
      .order('date', { ascending: false })

    if (reportsError) throw reportsError

    const reportCount = reports?.length || 0
    
    // Calculate basic metrics (you can expand this with more complex aggregations)
    const metrics = {
      reportCount,
      dateRange: { startDate, endDate },
      // Add more metrics as needed from reports
    }

    // Generate simple HTML email (or call your existing email generation logic)
    const dateRangeStr = `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #1e3a5f; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .content { background: #f8f9fa; padding: 20px; border-radius: 0 0 8px 8px; }
    .stat { background: white; padding: 15px; margin: 10px 0; border-radius: 4px; border-left: 4px solid #1e3a5f; }
    .footer { text-align: center; color: #666; font-size: 12px; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📈 Weekly Project Health Report</h1>
      <p>${dateRangeStr}</p>
    </div>
    <div class="content">
      <div class="stat">
        <strong>Reports Submitted:</strong> ${reportCount}
      </div>
      <p>This is an automated weekly summary from the Pipe-Up Pipeline Inspector platform.</p>
      <p>For more detailed information, please visit <a href="https://app.pipe-up.ca">app.pipe-up.ca</a></p>
    </div>
    <div class="footer">
      <p>This email was automatically generated by Pipe-Up Platform</p>
    </div>
  </div>
</body>
</html>
    `.trim()

    if (!RESEND_API_KEY) {
      return new Response(
        JSON.stringify({ error: 'RESEND_API_KEY not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Send email via Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Pipe-Up Reports <noreply@pipe-up.ca>', // Verified domain in Resend
        to: executiveEmails,
        subject: `📈 Weekly Project Health Report - ${dateRangeStr}`,
        html: htmlContent,
      }),
    })

    const result = await response.json()

    if (!response.ok) {
      console.error('Resend API error:', result)
      return new Response(
        JSON.stringify({ error: 'Failed to send email', details: result }),
        { status: response.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        messageId: result.id,
        emailsSent: executiveEmails,
        dateRange: { startDate, endDate },
        reportCount
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Edge function error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
