// constants.js - Pipeline Inspector Report Constants
// Extracted from InspectorReport.jsx for cleaner code organization

// Project configuration - FortisBC Eagle Mountain - Woodfibre Gas Pipeline
export const PROJECT_NAME = "FortisBC EGP - Eagle Mountain Woodfibre Gas Pipeline"
export const PROJECT_SHORT = "EGP"

// Pipeline locations for weather lookup - EGP Route (47km)
// KP 0+000 at Indian Arm (north end) to KP 47+000 at Woodfibre LNG Facility (Squamish)
export const pipelineLocations = {
  'Indian Arm 0+000 to 12+000': { lat: 49.4667, lon: -122.8833, name: 'Indian Arm (Start)' },
  'Mid-North 12+000 to 24+000': { lat: 49.5500, lon: -123.0500, name: 'Mid-Route North' },
  'Mid-South 24+000 to 36+000': { lat: 49.6000, lon: -123.1500, name: 'Mid-Route South' },
  'Woodfibre 36+000 to 47+000': { lat: 49.6700, lon: -123.2500, name: 'Woodfibre LNG (End)' }
}

// Activity types for pipeline construction
export const activityTypes = [
  'Clearing',
  'Access',
  'Topsoil',
  'Grading',
  'Stringing',
  'Bending',
  'Welding - Mainline',
  'Welding - Section Crew',
  'Welding - Poor Boy',
  'Welding - Tie-in',
  'Coating',
  'Ditch',
  'Lower-in',
  'Backfill',
  'Tie-in Completion',
  'Cleanup - Machine',
  'Cleanup - Final',
  'Hydrostatic Testing',
  'HDD',
  'HD Bores',
  'Piling',
  'Equipment Cleaning',
  'Hydrovac',
  'Welder Testing'
]

// Quality fields per activity type (API 1169 based)
export const qualityFieldsByActivity = {
  'Clearing': [], // Handled by ClearingLog component
  'Access': [
    { name: 'accessWidth', label: 'Access Width (m)', type: 'number' },
    { name: 'surfaceCondition', label: 'Surface Condition', type: 'select', options: ['Good', 'Fair', 'Poor'] }
  ],
  'Topsoil': [
    { name: 'stripDepth', label: 'Strip Depth (cm)', type: 'number' },
    { name: 'stockpileLocation', label: 'Stockpile Location (KP)', type: 'text' }
  ],
  'Grading': [], // Handled by GradingLog component
  'Stringing': [
    { name: 'jointNumbers', label: 'Joint Numbers (from-to)', type: 'text' },
    { name: 'heatNumbers', label: 'Heat Numbers', type: 'text' },
    { name: 'coatingCondition', label: 'Coating Condition', type: 'select', options: ['Good', 'Damaged - Repaired', 'Damaged - Flagged'] },
    { name: 'millCertVerified', label: 'Mill Cert Verified', type: 'select', options: ['Yes', 'No'] }
  ],
  'Bending': [
    { name: 'bendAngle', label: 'Bend Angle (°)', type: 'number' },
    { name: 'bendRadius', label: 'Bend Radius (m)', type: 'number' },
    { name: 'ovalityPercent', label: 'Ovality %', type: 'number' },
    { name: 'wrinkleCheck', label: 'Wrinkle Check', type: 'select', options: ['Pass', 'Fail', 'N/A'] },
    { name: 'bendTemp', label: 'Temperature (°C)', type: 'number' },
    { name: 'distanceToWeld', label: 'Distance to Nearest Weld (m)', type: 'number' }
  ],
  'Welding - Mainline': [
    { name: 'weldNumber', label: 'Weld Number', type: 'text' },
    { name: 'welderID', label: 'Welder ID', type: 'text' },
    { name: 'wpsNumber', label: 'WPS Number', type: 'text' },
    { name: 'preheatTemp', label: 'Preheat Temp (°C)', type: 'number' },
    { name: 'ndtType', label: 'NDT Type', type: 'select', options: ['RT', 'UT', 'MT', 'PT', 'None'] },
    { name: 'ndtResult', label: 'NDT Result', type: 'select', options: ['Accept', 'Reject', 'Pending'] },
    { name: 'repairRequired', label: 'Repair Required', type: 'select', options: ['Yes', 'No'] },
    { name: 'repairType', label: 'Repair Type', type: 'select', options: ['N/A', 'Root', 'Hot Pass', 'Fill', 'Cap', 'Full Cutout'] },
    { name: 'repairPass', label: 'Repair Pass #', type: 'text' },
    { name: 'rootOpening', label: 'Root Opening (mm)', type: 'number' },
    { name: 'hiLo', label: 'Hi-Lo (mm)', type: 'number' },
    { name: 'gap', label: 'Gap (mm)', type: 'number' }
  ],
  'Welding - Tie-in': [], // Handled by CounterboreTransitionLog component
  'Coating': [], // Handled by CoatingLog component
  'Ditch': [], // Handled by DitchLog component
  'Lower-in': [
    { name: 'paddingDepth', label: 'Padding Depth (cm)', type: 'number' },
    { name: 'depthOfCover', label: 'Depth of Cover (m)', type: 'number' },
    { name: 'clearance', label: 'Clearance from Foreign Lines (m)', type: 'number' },
    { name: 'liftPlanVerified', label: 'Lift Plan Verified', type: 'select', options: ['Yes', 'No'] },
    { name: 'equipmentInspected', label: 'Equipment Inspected', type: 'select', options: ['Yes', 'No'] }
  ],
  'Backfill': [
    { name: 'liftThickness', label: 'Lift Thickness (cm)', type: 'number' },
    { name: 'compactionPercent', label: 'Compaction %', type: 'number' },
    { name: 'rockShield', label: 'Rock Shield Used', type: 'select', options: ['Yes', 'No', 'N/A'] }
  ],
  'Tie-in Completion': [], // Handled by TieInCompletionLog component
  'Cleanup - Machine': [
    { name: 'gradingComplete', label: 'Grading Complete', type: 'select', options: ['Yes', 'No', 'In Progress'] },
    { name: 'debrisRemoved', label: 'Debris Removed', type: 'select', options: ['Yes', 'No', 'In Progress'] }
  ],
  'Cleanup - Final': [
    { name: 'seedingComplete', label: 'Seeding Complete', type: 'select', options: ['Yes', 'No', 'In Progress'] },
    { name: 'fencingRestored', label: 'Fencing Restored', type: 'select', options: ['Yes', 'No', 'N/A'] }
  ],
  'HDD': [], // Handled by HDDLog component
  'Piling': [], // Handled by PilingLog component
  'Equipment Cleaning': [], // Handled by EquipmentCleaningLog component
  'Hydrovac': [], // Handled by HydrovacLog component
  'Welder Testing': [], // Handled by WelderTestingLog component
  'Hydrostatic Testing': [], // Handled by HydrotestLog component
  'HD Bores': [
    { name: 'boreLength', label: 'Bore Length (m)', type: 'number' },
    { name: 'casingSize', label: 'Casing Size (in)', type: 'number' },
    { name: 'carrierPipeSize', label: 'Carrier Pipe Size (in)', type: 'number' },
    { name: 'annularSpace', label: 'Annular Space Filled', type: 'select', options: ['Yes', 'No'] }
  ]
}

// Time lost reasons
export const timeLostReasons = [
  'Weather',
  'Environmental',
  'Landowner Concerns',
  'Move Arounds',
  'Material Lay',
  'Safety Issue',
  'Equipment Breakdown',
  'Waiting on Materials',
  'Other'
]

// Labour classifications from CX2-FC contract (72 classifications)
export const labourClassifications = [
  'APPRENTICE OPER/OILER',
  'ASSISTANT PROJECT ENGINEER',
  'ASSISTANT SUPERINTENDENT',
  'BUS/ CREWCAB DRIVER',
  'CAMP MANAGER',
  'CONSTRUCTION MANAGER',
  'COST PLANNER/SCHEDULER',
  'DUMP TRUCK DRIVER 12-23 Yds',
  'ENGINEERING MANAGER',
  'ENVIRONMENTAL COORDINATOR',
  'EQUIPMENT CLERK',
  'EQUIPMENT MANAGER',
  'FIELD ENGINEER',
  'FLAT DECK < 5 TON',
  'FORKLIFT DRIVER (WAREHOUSE)',
  'FRONT-END/TIE-IN WELDER ON AUTO WELD SPREAD',
  'FRONT-END/TIE-IN WELDER ON STICK WELD SPREAD',
  'FUEL TRUCK DRIVERS HELPER',
  'FUEL/ WATER TRUCK DRIVER',
  'GENERAL FOREMAN',
  'GENERAL LABOURER',
  'INTERMEDIATE OPER',
  'LABOURER JOB STEWARD',
  'LANDMAN',
  'LOWBED/MULTIPURPOSE DRIVER',
  'MASTER MECHANIC',
  'MECH./SERVICE/ UTILITY WELD HELPER',
  'MECHANIC/ SERVICEMAN/ LUBEMAN',
  'MECHANIC/SERVICEMAN/LUBEMAN (NIGHT SHIFT)',
  'NIGHT WATCHMAN/ SECURITY',
  'NON-WELDER JOURNEYMAN/ FITTER ON AUTO WELD SPREAD',
  'NON-WELDER JOURNEYMAN/ FITTER ON STICK WELD SPREAD',
  'OFFICE CLERK',
  'OFFICE CLERK (LOCAL HIRE)',
  'OFFICE MANAGER',
  'OPERATOR JOB STEWARD',
  'PAYMASTER',
  'PICKER TRUCK DRIVER > 12 TON',
  'PICKUP/ PILOT CAR DRIVER',
  'PNEUMATIC TOOLS/NOZZLEMAN',
  'POWERSAW OPERATOR',
  'PRINC. OPER 1 (NIGHT SHIFT)',
  'PRINCIPAL OPER 1',
  'PRINCIPAL OPER 2',
  'PROJECT ADMINISTRATOR',
  'PROJECT ENGINEER',
  'PROJECT PLANNER',
  'PURCHASING AGENT',
  'QUALITY CONTROL SUPERVISOR',
  'QUALITY CONTROL TECHNICIAN',
  'SAFETY COORDINATOR',
  'SENIOR SAFETY COORDINATOR',
  'SET-IN/SET UP DRIVERS (BEND & WELD)',
  'SPEC LABOUR (CARPENTER, ETC.)',
  'STRAW - FITTER ON AUTO WELD SPREAD',
  'STRAW - FITTER ON STICK WELD SPREAD',
  'STRAW - LABOURER',
  'STRAW - OPERATOR',
  'SUPERINTENDENT',
  'SWAMPER/DRILL HELPER',
  'TEAMSTER - STEWARD',
  'TRANSPORTATION COORDINATOR',
  'UA JOB STEWARD ON AUTO WELD SPREAD',
  'UA LOWER-IN FOREMAN',
  'UA PIPE FOREMAN',
  'UA TEST FOREMAN',
  'UA TIE-IN FOREMAN',
  'UA WELDER FOREMAN',
  'UTILITY WELDER',
  'WAREHOUSEMAN 1',
  'WAREHOUSEMAN 2',
  'WELDER HELPER'
]

// Equipment types from CX2-FC contract (323 types)
export const equipmentTypes = [
  '100Kw Generator',
  '1 Ton Sandblast Unit',
  '2 Ton Sandblast Unit',
  '2" Water Pump',
  '42" Mandrel',
  '5 Ton Sandblast Unit',
  '5 Ton Stake Truck',
  '60\' Portable Bridge',
  'Air Booster',
  'Air Compressor - 1000 CFM',
  'Air Compressor - 1000 CFM x 350 PSI',
  'Air Compressor - 1200 CFM',
  'Air Compressor - 1250 CFM x 350 PSI (Oil Free)',
  'Air Compressor - 1300 CFM x 365 PSI',
  'Air Compressor - 150 to 185 CFM',
  'Air Compressor - 1500 CFM',
  'Air Compressor - 200 to 250 CFM',
  'Air Compressor - 300 to 400 CFM',
  'Air Compressor - 780 to 850 CFM',
  'Air Compressor - 900 CFM',
  'Air Compressor - 900 CFM x 350 PSI',
  'Air Dryer - 2600 CFM x 350 PSI',
  'Almand Heater',
  'ARGO ATV Side By Side',
  'Articulated Dump Truck - 30 Ton',
  'Articulated Dump Truck - 35 Ton',
  'Articulated Dump Truck - 40 Ton',
  'Athey Wagon',
  'Athey Wagon - 30 Tonne',
  'ATV/Gator',
  'Automatic Welding Tractor',
  'Automobile',
  'Backfill Blade Attach. for Cat 330-345 Hoes',
  'Backhoe - Cat 315 (or equivalent)',
  'Backhoe - Cat 320 (or equivalent)',
  'Backhoe - Cat 322 (or equivalent)',
  'Backhoe - Cat 324 (or equivalent)',
  'Backhoe - Cat 325 (or equivalent)',
  'Backhoe - Cat 329 (or equivalent)',
  'Backhoe - Cat 330 (or equivalent)',
  'Backhoe - Cat 330 c/w Thumb',
  'Backhoe - Cat 330 Longstick',
  'Backhoe - Cat 336 (or equivalent)',
  'Backhoe - Cat 345 (or equivalent)',
  'Backhoe - Cat 345 c/w Thumb',
  'Backhoe - Cat 345 Longstick',
  'Backhoe - Cat 365',
  'Backhoe - Cat 374',
  'Backhoe - Hitachi 870LC',
  'Backhoe - Link Belt 1400 Long Stick',
  'Bending Machine 16-30"',
  'Bending Machine 20-36"',
  'Bending Machine 32-42"',
  'Bending Machine 36-48"',
  'Boat & Motor',
  'Booster for Lowboy',
  'Bus',
  'Cable Clam/Board - LS 98 Linkbelt',
  'Cabbed Argo Side by Side c/w Trailer',
  'Coating Pre-Heat Generator & Coil',
  'Coating Truck - 5 Ton',
  'Compressor Hoses - 2" x 50\'',
  'Compressor Trailer',
  'Cradle Bore Machine & Auger',
  'CRC Auto Weld Pack',
  'Crewcab - 1 Ton',
  'Crewcab - 3/4 Ton',
  'Diesel Generator 185Kw',
  'Diesel Heater 390,000 BTU',
  'Ditch Witch 1330 & Trailer',
  'Ditching Wheel - BG 930',
  'Ditching Wheel - Jetco 7254',
  'Ditching Wheel - McKenzie 710',
  'Ditching Wheel - TA 77',
  'Ditching Wheel - Trenco 1360',
  'Ditching Wheel Trailer',
  'Dozer - Bush Rake Attachment',
  'Dozer - Cat U Blade',
  'Dozer - D10 (or equivalent)',
  'Dozer - D4 (or equivalent)',
  'Dozer - D4 LGP (or equivalent)',
  'Dozer - D5 (or equivalent)',
  'Dozer - D5 LGP (or equivalent)',
  'Dozer - D6H (or equivalent)',
  'Dozer - D6N (or equivalent)',
  'Dozer - D6N LGP (or equivalent)',
  'Dozer - D6R (or equivalent)',
  'Dozer - D6R LGP (or equivalent)',
  'Dozer - D6T (or equivalent)',
  'Dozer - D6T LGP (or equivalent)',
  'Dozer - D7E (or equivalent)',
  'Dozer - D7R (or equivalent)',
  'Dozer - D7R LGP (or equivalent)',
  'Dozer - D8T (or equivalent)',
  'Dozer - D9T (or equivalent)',
  'Dual 100 Kw Generator',
  'Dual 60 Kw Generator',
  'Enviro-Pads',
  'Farm Implement - Brush Hog',
  'Farm Implement - Chisel Plow',
  'Farm Implement - Cultivator',
  'Farm Implement - Disc',
  'Farm Implement - Mower',
  'Farm Implement - Post Pounder',
  'Farm Implement - Rock Picker',
  'Farm Implement - Rock Rake',
  'Farm Implement - Subsoiler',
  'Farm Tractor - Challenger 75',
  'Farm Tractor - Challenger MT844',
  'Farm Tractor - Challenger MT845',
  'Farm Tractor - Wheel < 100 HP',
  'Farm Tractor - Wheel > 100 HP',
  'Fence Truck - 1 Ton',
  'Fill Pipe - 8" (2.5Km)',
  'Fill Pipe - Load of 660 m',
  'Flatdeck - 1 Ton',
  'Flatdeck - 2 Ton',
  'Flatdeck - 3 Ton',
  'Flatdeck - 5 Ton',
  'Flatdeck - 8 Ton',
  'Flatdeck Bottle Truck',
  'Floc Water Tank',
  'Forklift - Zoom Boom',
  'Frozen Topsoil Cutter (Attachment)',
  'Fuel Tank',
  'Fuel Tank - 2500 Litre Skid',
  'Fuel Truck - Single Axle',
  'Fuel Truck - Tandem',
  'Gas Powered Auger',
  'Generator - 10 kW',
  'Generator - 100 kW',
  'Generator - 20 kW',
  'Generator - 2500 Watt',
  'Generator - 30 kW',
  'Generator - 3000 Watt',
  'Generator - 3500 Watt',
  'Generator - 5 kW',
  'Generator - 5000 Watt',
  'Generator - 60 kW',
  'Generator - 6500 Watt',
  'Generator Pump & Light 15-20kW',
  'Generator Pump & Light 8-10kW',
  'Generator Pump Pkg 35kW',
  'Generator Pump Pkg 75kW',
  'Grader - Cat G12',
  'Grader - Cat G14',
  'Grader - Cat G140',
  'Grader - Cat G16',
  'Grader - Cat G160',
  'Highboy Trailer',
  'Hoe - Bucket Rake Attachment',
  'Hoe - Chuck Blade Attachment',
  'Hoe Pac Attachment for Cat 324-336 Hoes',
  'Hoe Ram Attachment for Cat 330/345',
  'Hydraulic Clam - Cat 330 Longstick',
  'Hydraulic Road Sweeper',
  'Hydrovac Truck',
  'Induction Coil',
  'Jeep for Lowboy',
  'Light Tower - 6 kW',
  'Light Tower - 20 kW',
  'Lincoln Welder',
  'Loader - Cat 930',
  'Loader - Cat 950',
  'Loader - Cat 966',
  'Loader - Cat 980',
  'Loader - Cat 988',
  'Loader - Cat IT 28',
  'Loader - Cat IT 38',
  'Loader - Cat IT 62',
  'Loader Attachment - Pipe/Pole Grapple',
  'Lowboy Trailer',
  'Lowboy Trailer (40 Wheeler)',
  'Lowboy Trailer (48 Wheeler)',
  'Lowboy/Highboy Truck Tractor',
  'Mainline Sandblast Unit - Dual',
  'Mandrel',
  'Mechanics Rig',
  'Mulcher',
  'Nodwell - 6 Man & Mat. Size',
  'Non-Articulated Dump Truck',
  'Office Trailer',
  'Ozzie Padder',
  'Packer - Crowfoot',
  'Panther T8 All Terrain Dump Vehicle',
  'Picker - 45 Ton',
  'Picker Truck - 8 Ton',
  'Picker Truck - 10 Ton',
  'Picker Truck - 12 Ton',
  'Picker Truck - 15 Ton',
  'Picker Truck - 17 Ton',
  'Picker Truck - 25 Ton',
  'Picker Truck - 30 Ton',
  'Picker/Hiab Truck - 1 Ton',
  'Picker/Hiab Truck - 3 Ton',
  'Pickup - 1/2 Ton',
  'Pickup - 3/4 Ton',
  'Pigging Head (10")',
  'Pigging Head (16")',
  'Pigging Head (20")',
  'Pigging Head (24")',
  'Pigging Head (30")',
  'Pigging Head (36")',
  'Pigging Head (42")',
  'Pipe Ramming Tool',
  'Pipe Rollers (80,000lb)',
  'Pipeline Roller Cradles (Each)',
  'Plate Tamper - Walk Behind (1000Lb)',
  'Pole Trailer',
  'Portable Bridge 60"',
  'Portable Heater BT400-460H',
  'Portable Plug In Panel with Generator',
  'Portable Shop',
  'Portable Shop Heater - Allmand',
  'Power Dozer',
  'Power Unit for Induction Coil',
  'Powersaw',
  'Pressure Washer - Landa MCV4',
  'Propane Station Unit',
  'Propane/Preheat Truck',
  'Rake - Hoe Attachment',
  'Rig Mat - 8\' x 20\'',
  'Rig Mat - 8\' x 30\'',
  'Rig Mat - 8\' x 40\'',
  'Ripper Shank for Cat 345 Backhoe',
  'Rock Splitter',
  'Roller Packer 90" Contour',
  'Rolli Cradles & Spreader Bars',
  'Rubber Tired Hoe',
  'Rubber Tired Hoe - Cat 420/430',
  'Scissor Neck Trailer',
  'Screw Anchor Attachment (Single) to Hoe',
  'Self Centering Pallet Forks',
  'Service Truck',
  'Shamrock Backhoe 320',
  'Sheeps Foot Drum Packer',
  'Shoring Box',
  'Sideboom - Cat 561/PL61',
  'Sideboom - Cat 571',
  'Sideboom - Cat 572',
  'Sideboom - Cat 572R',
  'Sideboom - Cat 583',
  'Sideboom - Cat 583T',
  'Sideboom - Cat 587T',
  'Sideboom - Cat 594',
  'Sideboom - Liebherr RL64',
  'Silt Fence Installation Attachment',
  'Skagit',
  'Skid Mounted - Mainline Coating Unit',
  'Skid Sloop',
  'Skid Steer',
  'Skid Truck Tractor',
  'Sled',
  'Slop Tanks',
  'Sno Cat',
  'Sno Cat - Piston Bully PF 300',
  'Snow Making Equipment',
  'Snowmobile',
  'Snowplow/Sander Truck',
  'Solar Road Sign Boards',
  'Spray Coating Truck',
  'Stepdeck Trailer',
  'Storage Containers',
  'Storage Trailer/Van',
  'Stringing Truck Tractor',
  'Strong Box Snow Pusher',
  'Suburban',
  'Surge Tank',
  'Swamp Mats (Set of 4)',
  'Swenson Spreader',
  'Tag-A-Long Trailer (6 Ton)',
  'Tag-A-Long Trailer (10 Ton)',
  'Tag-A-Long Trailer (20 Ton)',
  'Tag-A-Long Trailer (Farm Wagon)',
  'Tag-A-Long Trailer (Utility)',
  'Tesmac Ditcher',
  'Test - 1" Squeeze Pump',
  'Test - 3" Squeeze Pump',
  'Test - Boiler',
  'Test - Fill Pump 6 x 6',
  'Test - Fill Pump 8 x 6',
  'Test - Fill Pump 10 x 8',
  'Test - Honda Squeeze Pump',
  'Test Trailer & Instrumentation',
  'Texas Winch Truck',
  'Track Bore Machine & Auger',
  'Track Morooka',
  'Trailer - B-Train',
  'Transition Machine (Includes Power Unit)',
  'Transition Machine (Without Power Unit)',
  'Trombone Trailer',
  'Utility Welder Rig',
  'Viking Power Dozer',
  'Wacker 1301 - Ground Heater and Generator',
  'Warehouse Trailer/Van',
  'Warehouse Trailer/Van Diesel Heated Storage',
  'Wash Unit - Steam, Water Truck',
  'Washroom Trailer',
  'Water Canon',
  'Water Pump - 2"',
  'Water Pump - 3"',
  'Water Pump - 4"',
  'Water Pump - 6"',
  'Water Pump - 8"',
  'Water Pump - 10" Electric',
  'Water Tank Trailer',
  'Water Tank for Test',
  'Water Truck',
  'Weld - Auto Repair Shack',
  'Weld - Buffing Tractor (ATV Style)',
  'Weld - Internal Repair Unit',
  'Weld - Quad Welder/Tack Rig',
  'Weld - Sleigh',
  'Weld - Weld Platform (Attachment)',
  'Weld - Welding Shack',
  'Welding Machine',
  'Welding Rig'
]

// Create empty activity block
export function createEmptyActivity() {
  return {
    id: Date.now() + Math.random(),
    activityType: '',
    contractor: '',
    foreman: '',
    ticketNumber: '',
    startKP: '',
    endKP: '',
    metersToday: '',
    metersPrevious: '',
    metersToDate: '',
    workDescription: '',
    labourEntries: [],
    equipmentEntries: [],
    qualityData: {},
    workPhotos: [],
    timeLostReason: '',
    timeLostHours: '',
    timeLostDetails: ''
  }
}
