-- LEM 18204 - Wade Cocks - Bending Crew
INSERT INTO contractor_lems (
    organization_id,
    project_id,
    field_log_id,
    account_number,
    foreman,
    date,
    labour_entries,
    equipment_entries,
    total_labour_cost,
    total_equipment_cost
) VALUES (
    (SELECT id FROM organizations WHERE slug = 'demo'),
    (SELECT id FROM projects WHERE short_code = 'DPP'),
    '18204',
    'CLX2130',
    'Wade Cocks',
    '2014-01-20',
    '[
      {"employee_id": "3370", "name": "Brent Lavallee", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "3681", "name": "Brett Chern", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1162", "name": "Brett Uhrich", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1147", "name": "Casey Griffin", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "3189", "name": "Colin Gillard", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1126", "name": "Dustin Hanson", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "3291", "name": "Henry Grignon", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "3422", "name": "Herbert Cassel", "type": "Bus Driver", "rt_hours": 8.0, "rt_rate": 56.73, "ot_hours": 5.0, "ot_rate": 85.10},
      {"employee_id": "1161", "name": "Jay Fornal", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "1123", "name": "Joseph Herman", "type": "Journeyman / Fitter", "rt_hours": 8.0, "rt_rate": 69.01, "ot_hours": 5.0, "ot_rate": 103.51},
      {"employee_id": "3340", "name": "Lukas Stewart", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 5.0, "ot_rate": 72.15},
      {"employee_id": "1130", "name": "Nathan Stewart", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "1151", "name": "Raymund Ventanilla", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1164", "name": "Reed Fornal", "type": "Straw (Labourer)", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 5.0, "ot_rate": 72.15},
      {"employee_id": "3947", "name": "Riley Griffin", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "1131", "name": "Russell Jackson", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "3448", "name": "Ryan Slater", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "3921", "name": "Sam Tang", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1128", "name": "Wade Cocks", "type": "General Foreman (OPR)", "rt_hours": 1.0, "rt_rate": 1332.16, "ot_hours": 0.0, "ot_rate": 0.0}
    ]'::jsonb,
    '[
      {"equipment_id": "SA8-001A", "type": "(FT) MANDRELS, DYES, SHOES", "hours": 1.0},
      {"equipment_id": "SA8-003", "type": "ATHEY WAGON", "hours": 1.0},
      {"equipment_id": "OR1282", "type": "BENDING MACHINE 32-42", "hours": 1.0},
      {"equipment_id": "SA8-001", "type": "BENDING MACHINE 36-48", "hours": 1.0},
      {"equipment_id": "OR1132", "type": "BUS", "hours": 1.0},
      {"equipment_id": "OR1061", "type": "CREWCAB - 1 TON", "hours": 1.0},
      {"equipment_id": "OR1073", "type": "CREWCAB - 1 TON", "hours": 1.0},
      {"equipment_id": "OR1002", "type": "CREWCAB 3/4 TON", "hours": 1.0},
      {"equipment_id": "SB308", "type": "SIDEBOOM - CAT 583", "hours": 1.0},
      {"equipment_id": "SB309", "type": "SIDEBOOM - CAT 583", "hours": 1.0},
      {"equipment_id": "SA7-003", "type": "SIDEBOOM - CAT 583T", "hours": 1.0},
      {"equipment_id": "SA7-007", "type": "SIDEBOOM - CAT 583T", "hours": 1.0}
    ]'::jsonb,
    15000.00,
    8500.00
);

-- LEM 18205 - Shaun Cook - Lower-In Crew
INSERT INTO contractor_lems (
    organization_id,
    project_id,
    field_log_id,
    account_number,
    foreman,
    date,
    labour_entries,
    equipment_entries,
    total_labour_cost,
    total_equipment_cost
) VALUES (
    (SELECT id FROM organizations WHERE slug = 'demo'),
    (SELECT id FROM projects WHERE short_code = 'DPP'),
    '18205',
    'CLX2180',
    'Shaun Cook',
    '2014-01-20',
    '[
      {"employee_id": "3363", "name": "Barry Hyslop", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "1387", "name": "Benoit Ouellet", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 6.0, "ot_rate": 96.36},
      {"employee_id": "3665", "name": "Carl Payne", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 5.0, "ot_rate": 72.15},
      {"employee_id": "3123", "name": "Dave Nemec", "type": "Apprentice Operator", "rt_hours": 8.0, "rt_rate": 49.44, "ot_hours": 5.0, "ot_rate": 74.16},
      {"employee_id": "3478", "name": "Duncan Kozlok-McGreish", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 5.0, "ot_rate": 96.36},
      {"employee_id": "3990", "name": "Edgar Crossman", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "4005", "name": "Isse Shalye", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 4.0, "ot_rate": 72.15},
      {"employee_id": "1438", "name": "John Long", "type": "General Labourer", "rt_hours": 8.0, "rt_rate": 48.10, "ot_hours": 6.0, "ot_rate": 72.15},
      {"employee_id": "3685", "name": "Michael McKague", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "3988", "name": "Miguel Mallais", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 5.0, "ot_rate": 96.36},
      {"employee_id": "1428", "name": "Randy Andrews", "type": "Apprentice Operator", "rt_hours": 8.0, "rt_rate": 49.44, "ot_hours": 6.0, "ot_rate": 74.16},
      {"employee_id": "3459", "name": "Rick (Earl) Carrigan", "type": "Bus Driver", "rt_hours": 8.0, "rt_rate": 56.73, "ot_hours": 5.0, "ot_rate": 85.10},
      {"employee_id": "1345", "name": "Ryan Quibell", "type": "Journeyman / Fitter (Auto)", "rt_hours": 8.0, "rt_rate": 69.01, "ot_hours": 5.0, "ot_rate": 103.51},
      {"employee_id": "3471", "name": "Salvatore Schifano", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "3981", "name": "Shane Desbiens", "type": "Principal Operator 1", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 4.0, "ot_rate": 96.36},
      {"employee_id": "1347", "name": "Shaun Cook", "type": "UA Lower-In Foreman", "rt_hours": 1.0, "rt_rate": 1952.31, "ot_hours": 0.0, "ot_rate": 0.0},
      {"employee_id": "1348", "name": "Wendy Cook", "type": "Straw (Operator)", "rt_hours": 8.0, "rt_rate": 64.24, "ot_hours": 7.0, "ot_rate": 96.36}
    ]'::jsonb,
    '[
      {"equipment_id": "AT02", "type": "ATHEY WAGON", "hours": 1.0},
      {"equipment_id": "OR1790", "type": "BACKHOE CAT 315 (OR EQUIVALENT)", "hours": 1.0},
      {"equipment_id": "OR1791", "type": "BACKHOE CAT 330 LONGSTICK", "hours": 1.0},
      {"equipment_id": "OR1661", "type": "BACKHOE CAT 345BL/CL LONGSTICK", "hours": 1.0},
      {"equipment_id": "OR1074", "type": "CREWCAB - 1 TON", "hours": 1.0},
      {"equipment_id": "OR1750", "type": "CREWCAB - 1 TON", "hours": 1.0},
      {"equipment_id": "OR1702", "type": "CREWCAB 3/4 TON", "hours": 1.0},
      {"equipment_id": "OR1709", "type": "CREWCAB 3/4 TON", "hours": 1.0},
      {"equipment_id": "OR1077", "type": "FLATDECK - 1 TON", "hours": 1.0},
      {"equipment_id": "OR1458", "type": "LIGHT TOWER - 6KW", "hours": 1.0},
      {"equipment_id": "OR1805", "type": "PIPE ROLLER CRADLES (Each)", "hours": 1.0},
      {"equipment_id": "OR1806", "type": "PIPE ROLLER CRADLES (Each)", "hours": 1.0},
      {"equipment_id": "OR1807", "type": "PIPE ROLLER CRADLES (Each)", "hours": 1.0},
      {"equipment_id": "OR1808", "type": "PIPE ROLLER CRADLES (Each)", "hours": 1.0},
      {"equipment_id": "SA7-010", "type": "SIDEBOOM - CAT 583T", "hours": 1.0},
      {"equipment_id": "OR1784", "type": "SIDEBOOM - CAT 587T", "hours": 1.0},
      {"equipment_id": "OR1785", "type": "SIDEBOOM - CAT 587T", "hours": 1.0},
      {"equipment_id": "OR1786", "type": "SIDEBOOM - CAT 587T", "hours": 1.0},
      {"equipment_id": "OR1629", "type": "Sideboom - Cat 594", "hours": 1.0},
      {"equipment_id": "SB404", "type": "SIDEBOOM - CAT 594", "hours": 1.0}
    ]'::jsonb,
    18000.00,
    12000.00
);
